spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bartender
    username: root
    password: sebas123
  jpa:
    hibernate.ddl-auto: none
    show-sql: true